FROM rust:1.92.0-bullseye@sha256:c6d501c039204c21e9fa374f234bd41bdc8b36cfd455a407ef145d9bef19f2b7 AS builder
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
WORKDIR /tmp/acars-bridge

RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev
COPY . .

RUN cargo build --release

FROM scratch
COPY --from=builder /tmp/acars-bridge/target/release/acars-bridge /acars-bridge
