FROM rust:1.98.0-bullseye@sha256:4730e387a220a08a365c77da3096544dde214f9d796c16284d4be45438cad4a9 AS builder
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
WORKDIR /tmp/acars-bridge

RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev
COPY . .

RUN cargo build --release

FROM scratch
COPY --from=builder /tmp/acars-bridge/target/release/acars-bridge /acars-bridge
